/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityZoneRouteImport } from './routes/activity-zone'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as FriendbotRouteImport } from './routes/friendbot'
import { Route as GuidebotRouteImport } from './routes/guidebot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityZoneRoute = ActivityZoneRouteImport.update({
  id: '/activity-zone',
  path: '/activity-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendbotRoute = FriendbotRouteImport.update({
  id: '/friendbot',
  path: '/friendbot',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidebotRoute = GuidebotRouteImport.update({
  id: '/guidebot',
  path: '/guidebot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-zone': typeof ActivityZoneRoute
  '/connect': typeof ConnectRoute
  '/friendbot': typeof FriendbotRoute
  '/guidebot': typeof GuidebotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-zone': typeof ActivityZoneRoute
  '/connect': typeof ConnectRoute
  '/friendbot': typeof FriendbotRoute
  '/guidebot': typeof GuidebotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-zone': typeof ActivityZoneRoute
  '/connect': typeof ConnectRoute
  '/friendbot': typeof FriendbotRoute
  '/guidebot': typeof GuidebotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity-zone' | '/connect' | '/friendbot' | '/guidebot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity-zone' | '/connect' | '/friendbot' | '/guidebot'
  id:
    | '__root__'
    | '/'
    | '/activity-zone'
    | '/connect'
    | '/friendbot'
    | '/guidebot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityZoneRoute: typeof ActivityZoneRoute
  ConnectRoute: typeof ConnectRoute
  FriendbotRoute: typeof FriendbotRoute
  GuidebotRoute: typeof GuidebotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-zone': {
      id: '/activity-zone'
      path: '/activity-zone'
      fullPath: '/activity-zone'
      preLoaderRoute: typeof ActivityZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friendbot': {
      id: '/friendbot'
      path: '/friendbot'
      fullPath: '/friendbot'
      preLoaderRoute: typeof FriendbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidebot': {
      id: '/guidebot'
      path: '/guidebot'
      fullPath: '/guidebot'
      preLoaderRoute: typeof GuidebotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityZoneRoute: ActivityZoneRoute,
  ConnectRoute: ConnectRoute,
  FriendbotRoute: FriendbotRoute,
  GuidebotRoute: GuidebotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
